# SPDX-FileCopyrightText: Magenta ApS
# SPDX-License-Identifier: MPL-2.0

version: "3.9"
services:
  engagement-updater:
    build: .
    command: ["uvicorn", "--factory", "app.main:create_app", "--host", "0.0.0.0", "--reload"]
    environment:
      AMQP__URL: "amqp://guest:guest@msg_broker:5672/"
      AUTH_SERVER: "http://keycloak:8080/auth"
      MO_URL: "http://mo"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      ASSOCIATION_TYPE: "automatisk_oprettet"
    networks:
      - os2mo_default
    ports:
      - "8000:8000"
    volumes:
      - ./engagement_updater:/opt/app/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://engagement_updater:8000/metrics"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  init:
    image: magentaaps/os2mo-init:latest
    environment:
      AUTH_SERVER: "http://keycloak:8080/auth"
      MO_URL: "http://mo"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      LORA_URL: "http://mox"
      LORA_CLIENT_SECRET: "a091ed82-6e82-4efc-a8f0-001e2b127853"
    networks:
      - os2mo_default
    volumes:
      - type: bind
        source: ./init.config.yaml
        target: /config/config.yml
        read_only: true

networks:
  os2mo_default:
    external: true
